using System;
using System.Collections.Generic;
using System.Linq;

namespace EvensAndOdds.ConsoleApp
{
    internal class MyClass
    {
        private static void Main(string[] args)
        {
            try
            {
                // Read input from stdin and provide input before running
                string line1 = Console.ReadLine().Trim();
                long N = long.Parse(line1);
                List<long> cases = new List<long>();

                for (int i = 0; i < N; i++)
                {
                    cases.Add(long.Parse(Console.ReadLine().Trim()));
                }

                // Process the list of cases generated by the code above.
                // sample code for writing to console: System.Console.WriteLine("Hello World!\n");
                foreach (long input in cases)
                {
                    List<int> arr = input.ToString().ToCharArray().Select(Convert.ToInt32).ToList();
                    bool even = arr.FindAll(a => a % 2 == 0).Count % 2 == 0;
                    bool odd = arr.FindAll(a => a % 2 == 1).Count % 2 == 1;
                    Console.WriteLine(even && odd ? "YES" : "NO");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex}");
            }
            finally
            {
                Console.WriteLine("--- Press Any Key To Continue ---");
                Console.ReadKey(true);
            }
        }
    }
}